###récupeer tous les clients
GET http://localhost:3000/client

###récuperer un client par ID
GET http://localhost:3000/client/Marie

### créé le client 
POST http://localhost:3000/client
Content-Type: application/json

{
    "nom":"Le Bras",
    "prenom":"Marie",
    "identifiant":"mlebras",
    "password":"admin"
}


#### modifier un client
PATCH http://localhost:3000/client

#### supprimer un client
DELETE http://localhost:3000/client/64bd53012db35c5ecc73bbd4

